---
isis_advertise_passive_only: true
isis_ti_lfa:
  enabled: true
  protection: node

custom_structured_configuration_ip_extcommunity_lists_regexp:
    EXT-BLOCK-TYPE-2:
      - type: permit
        regexp: "RT:65000:[1-9][0-9]{4}_"
      - type: permit
        regexp: "RT:65000:[1-9][0-9]{5}_"

custom_structured_configuration_prefix_lists:
  EXPORT-SCRUB-VXLAN-FABRIC-INTERNALS:
    sequence_numbers:
      10:
        action: permit 10.64.9.0/24 le 32
      20:
        action: permit 100.64.10.0/24 le 32
      30:
        action: permit 100.64.13.0/24 le 32
      40:
        action: permit 100.64.14.0/24 le 32

custom_structured_configuration_route_maps:
  RM-SCRUB-ROUTES-OUT:
    sequence_numbers:
      10:
        type: deny
        match:
          - "extcommunity EXT-BLOCK-TYPE-2"
      20:
        type: deny
        match:
          - "ip address prefix-list EXPORT-SCRUB-VXLAN-FABRIC-INTERNALS"
      30:
        type: permit

