---
- name: Build Switch configuration
  hosts: EXT_EOS_ROUTERS
  connection: local
  gather_facts: false
  vars:
    eos_config_dir: "router_configs"
  tasks:

    - name: replace configuration with intended configuration
      eos_config:
        src: "{{ eos_config_dir }}/{{ inventory_hostname }}.cfg"
        replace: config
        save_when: modified
        # backup: "{{ eos_config_deploy_eapi_pre_running_config_backup }}"
        # backup_options:
        #   filename: "{{ pre_running_config_backup_filename }}"
        #   dir_path: "{{ pre_running_config_backup_dir }}"
      # notify: "backup config"
      tags: [provision]