---
- name: Build Switch configuration
  hosts: MPLS_CORE
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp

  tasks:

    - name: generate intended variables
      tags: [build, provision, debug]
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, generate, debug]
      import_role:
        name: arista.avd.eos_cli_config_gen
      # when: structured_config.changed | arista.avd.default(true)

    - name: deploy configuration to device
      tags: [deploy, never]
      import_role:
        name: arista.avd.eos_config_deploy_eapi
      # check_mode: yes
